name: Sync Private Repo with Public Repo

on:
  # Triggers the workflow at regular intervals (e.g., every 6 hours)
  schedule:
    - cron: '0 */6 * * *'  # This runs the action every 6 hours

  # Allows manual triggering of the workflow
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Private Repository
        uses: actions/checkout@v3
        with:
          repository: yourusername/private-repo
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Public Repository as Upstream
        run: |
          git remote add upstream https://github.com/otherusername/repo-1.git
          git fetch upstream

      - name: Merge Public Repo Changes
        run: |
          git checkout main
          git merge upstream/main
          git push origin main
